# conda env create --file environment.yml
# mamba env create --file environment.yml
name: {{cookiecutter.project_slug}}
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
{% if cookiecutter.project_packages == "All" %}
  - black
  - invoke
  - jupyter
  - jupyterlab
  - keras
  - lightgbm
  - missingno
  - nbdime
  - pandas-flavor
  - pandas-profiling
  - plotly
  - pyjanitor
  - pylint
  - pyprojroot
  - pyspark
  - python-dotenv
  - statsmodels
  - tensorflow
{%endif -%}  
  - scikit-learn
  - seaborn
  - python={{cookiecutter.python_version}}
  - pip
  - pandas
